/*
 *  Source machine generated by GadToolsBox V1.4
 *  which is (c) Copyright 1991,92 Jaba Development
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_f1                                0
#define GD_f2                                1

#define Input_CNT 2

extern struct Screen        *Scr;
extern APTR                  VisualInfo;
extern struct Window        *InputWnd;
extern struct Gadget        *InputGList;
extern struct Gadget        *InputGadgets[Input_CNT];
extern struct Menu           *InputMenus;
extern UWORD                 InputLeft;
extern UWORD                 InputTop;
extern UWORD                 InputWidth;
extern UWORD                 InputHeight;
extern UBYTE                *ViewWdt;
extern UBYTE                *InputWdt;
extern struct TextAttr       thinpaz8;
extern UWORD                 InputGTypes[];
extern struct NewGadget      InputNGad[];
extern ULONG                 InputGTags[];


extern int OpenInputWindow( void );
extern void CloseInputWindow( void );
